---
# Version: 0.4
- name: Instalacion de paquetes inicial de maquinas nuevas
  hosts: all
  become: true
  tasks:

    - name: Actualizar cache APT
      apt:
        update_cache: true
        cache_valid_time: 3600
        force_apt_get: true
